// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error('Missing Supabase environment variables. Please check your .env file.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase: SupabaseClient<any> = createClient(
  SUPABASE_URL || '',
  SUPABASE_ANON_KEY || '',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        'X-Client-Info': 'metaconstrutor-web',
      },
    },
  }
);

const originalGetUser = supabase.auth.getUser.bind(supabase.auth);
supabase.auth.getUser = (async (...args: Parameters<typeof originalGetUser>) => {
  try {
    return await originalGetUser(...args);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error ?? '');
    if (!message.includes('Failed to fetch')) {
      throw error;
    }

    const { data } = await supabase.auth.getSession().catch(() => ({ data: { session: null } }));
    return {
      data: { user: data.session?.user ?? null },
      error: null,
    } as Awaited<ReturnType<typeof originalGetUser>>;
  }
}) as typeof supabase.auth.getUser;
